### ISSUE TITLE
Improve code block responsiveness by adjusting `.highlight pre` CSS

### ISSUE THREAD

**Issue by chriskyfung** [chriskyfung/amp-affiliately-jekyll-theme#125]
**Problem:**  
On mobile screens, code blocks with `white-space: pre-wrap;` in `.highlight pre` cause:  
- ✂️ **Forced line breaks** in the middle of code syntax (e.g., splitting URLs, long function names, or strings)  
- 📱 **Horizontal overflow** requiring awkward sideways scrolling on small screens  
- 🤏 **Unreadable formatting** when indentation/alignment breaks (critical for Python/YAML/etc)  

**Current Behavior (Mobile):**  
![Current mobile issue](https://github.com/user-attachments/assets/645f7026-cf5d-49cb-a4c1-53e2f68e151e)  
*(Screenshot shows code breaking mid-line on mobile view)*  

**Suggested Solution:**  
Update `.highlight pre` to:  
```css
.highlight pre {
  white-space: pre; /* Preserve original formatting */
  overflow-x: auto; /* Enable horizontal scrolling only when needed */
  max-width: 100%;  /* Respect parent container boundaries */
}
```  

**Benefits for Mobile:**  
✅ **No unexpected wrapping** – Code stays intact as written  
✅ **Cleaner scrolling** – Horizontal scroll appears only when necessary  
✅ **Better readability** – Maintains indentation/alignment for whitespace-sensitive code  
✅ **Responsive-friendly** – Adapts to different screen sizes  

**Example Comparison:**  

**After (pre + overflow-x):**  
![Expected mobile view](https://github.com/user-attachments/assets/b0820a94-9889-4374-a675-99774be68210)

**Additional Considerations:**  
1. Add `@media` queries for smaller screens if needed  
2. Test with popular mobile screen sizes (e.g., iPhone SE, Galaxy S23)  
3. Consider adding `padding: 1rem` for better mobile touch targets  

Would be happy to create a PR with these changes and cross-browser/mobile testing results.
