### ISSUE TITLE
🐛 Layout Issue: Metadata Overflow & Link Icon Misalignment in Desktop Article Cards (width > 768px)

### ISSUE THREAD

**Issue by chriskyfung** [chriskyfung/amp-affiliately-jekyll-theme#129]
The metadata section (**category, link icon**) in article cards experiences **vertical overflow** and **visual misalignment** on **desktop layouts (width > 768px)**. In the provided screenshot and HTML, the `.metafooter` section shows cramped spacing and inconsistent vertical alignment, particularly for cards with **longer titles or text content**, disrupting the card’s visual harmony.  

The issue appears exacerbated by fixed-height constraints in the SCSS for desktop breakpoints (e.g., `min-width: 992px`), which truncate or overflow content unpredictably. Additionally, the link icon (`fa-link`) sits **visibly lower** than adjacent text elements (e.g., category), creating visual dissonance.  

**Steps to Reproduce:**  
1. Resize browser viewport to **> 768px width** (desktop layout).  
2. Inspect the `.metafooter` section of cards with:  
   - Long card titles (e.g., `"Fix Netlify CLI & Node Task List \`ntl\` Conflict on Windows with Volta"`).  
   - Long-form category names (if implemented).  
3. Observe:  
   - **Vertical overflow**: Metadata (category, link icon) is pushed downward, breaking the card’s boundary or overlapping with other elements.  
   - **Link icon misalignment**: The `fa-link` icon sits visibly lower than text elements (category).  

**Expected Behavior:**  
- Metadata (**category, link icon**) should fit within the card’s footer **without vertical overflow** on desktop layouts.  
- The link icon (`fa-link`) should align vertically with text elements and maintain consistent spacing.  

**Actual Behavior:**  
- Longer titles or text content cause **vertical overflow** in `.metafooter`, creating uneven card heights and breaking visual boundaries.  
- The link icon (`fa-link`) sits **visibly lower** than text elements (e.g., category), creating visual misalignment.  

**Problematic SCSS Code:**  
The following SCSS rules in the `min-width: 992px` media query contribute to the issue:  
```scss
.listfeaturedtag .card {
  height: 260px; // Fixed height causes overflow for longer content
}
.wrapfooter {
  padding-left: 0;
  right: auto;
}
.wrapmeta {
  flex: 0 0 58.333333%; // Rigid width allocation
  max-width: 58.333333%;
}
.wrapthumbnail {
  flex: 0 0 41.666667%; // Rigid width allocation
  max-width: 41.666667%;
}
```  

**Proposed Fixes:**  
1. **Remove Fixed Height Constraints:**  
   Avoid hardcoding `.card` height to allow natural expansion:  
   ```scss
   @media (min-width: 992px) {
     .listfeaturedtag .card {
       height: auto; // Allow cards to grow with content
     }
   }
   ```  

2. **Fix Vertical Alignment for Metadata:**  
   Use `flex` to align `.metafooter` content and truncate overflowing text:  
   ```scss
   @media (min-width: 769px) {
     .wrapfooter {
       display: flex;
       align-items: center; // Vertically center items
       gap: 8px;
       overflow: hidden;
       padding-left: 1rem; // Add spacing from content edge
     }
     .category-class { // Adjust selector based on category implementation
       white-space: nowrap;
       overflow: hidden;
       text-overflow: ellipsis;
       max-width: 150px;
     }
   }
   ```  

3. **Align Link Icon with Text:**  
   Ensure the link icon aligns with adjacent text using `inline-flex`:  
   ```scss
   .post-read-more {
     display: inline-flex;
     align-items: center;
     margin-left: 8px;
     line-height: 1; // Prevent inherited line-height from affecting icon
   }
   .post-read-more i {
     font-size: 0.9rem;
     vertical-align: middle; // Align with text baseline
   }
   ```  

4. **Adjust Flexbox Proportions (Optional):**  
   Reduce rigidity in `.wrapmeta` and `.wrapthumbnail` for better responsiveness:  
   ```scss
   @media (min-width: 992px) {
     .wrapmeta {
       flex: 1 1 58.333333%; // Allow flexible growth
       max-width: none;
     }
     .wrapthumbnail {
       flex: 1 1 41.666667%; // Allow flexible growth
       max-width: none;
     }
   }
   ```  

**Additional Notes:**  
- Test fixes across all desktop breakpoints (`min-width: 768px`, `min-width: 992px`, `min-width: 1200px`).  
- If categories are dynamically added, ensure `.category-class` selectors match your implementation.  
- Verify that removing `height: 260px` does not break other layout assumptions (e.g., thumbnail alignment).  

Let’s address this to restore layout consistency! 🛠️
